### ISSUE TITLE
Create a script to update the rootcerts

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-payment-protocol#17]
Could pull data from
http://mxr.mozilla.org/mozilla-central/source/security/nss/lib/ckfw/builtins/certdata.txt 
or from
https://github.com/kirei/catt

**Comment by braydonf** [comment]
I believe there is a tool from v0.1 that needs to be migrated over still:
https://github.com/bitpay/bitcore/blob/v0.1/browser/root-certs
