### ISSUE TITLE
Payment Request: Can't figure out how generate a x509 certificate

### ISSUE THREAD

**Issue by ticruz38** [bitpay/bitcore-payment-protocol#29]
I just can't find a way to generate such file.
```javascript
var certificates = new PaymentProtocol().makeX509Certificates();
certificates.set('certificate', [file_with_x509_der_cert]);
````
Is there any utilities function in the bitcore-payment-protocol API to generate such x509_der_cent file?
I do not have any knowledge in such field, I just assume it has something to deal with HTTPS

**Comment by insanity54** [comment]
This is not something provided by Bitcore. It's a SSL certificate, the same exact thing used by websites to verify identity, and establish an encrypted session. BIP70 uses it to prevent man-in-the-middle attacks, by ensuring that the payment is going to the intended recipient. You can pay companies like GoDaddy for a SSL cert, or there are some free providers. I like the Linux Foundation's LetsEncrypt https://letsencrypt.org/howitworks/

**Comment by ticruz38** [comment]
Yes thank you, I'll give it a try! I'll close it since it has nothing to deal with that library.
