### ISSUE TITLE
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

### ISSUE THREAD

**Issue by insanity54** [bitpay/bitcore-payment-protocol#30]
I'm trying to follow this guide and [i][5]mplement a BIP70 payment protocol. https://bitcore.io/api/paypro 

In the guide, it shows two required steps which `bitcore-payment-protocol` does not provide functionality for. Those two things are:

1) creating a output

    details.set('outputs', outputs);

2) creating a script

    outputs.set('script', script.toBuffer()); // an instance of script

So naturally, I figure I need to use the bitcore-lib library to create an output and a script, to be able to implement BIP70 in Bitcore. So I require it like so:

```
var PaymentProtocol = require('bitcore-payment-protocol');
var BitcoreLib = require('bitcore-lib');
```

But that's a no-go, it just makes an error when running

```
$ node bitcoin.js
/Users/chrisgrimmett/scripts/loluwin/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
          ^
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/Users/chrisgrimmett/scripts/loluwin/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/Users/chrisgrimmett/scripts/loluwin/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chrisgrimmett/scripts/loluwin/bitcoin.js:2:18)
    at Module._compile (module.js:460:26)
```

Looking around at [other][1] [GitHub][2] [issues][3], and judging by the error message itself, the recommended fix seems to be to "check that submodules do not also include their own bitcore-lib dependency." However that doesn't seem possible in `bitcore-payment-protocol`...

[bitcore-payment-protocol is hard coded to require it's own instance of bitcore-lib][4] and doesn't export a handle, so I don't think I can stop it from including it's own, and I can't "tap into" that instance to implement what I think I need.

Am I doing something wrong?

[1]:https://github.com/bitpay/bitcore-node/issues/374
[2]:https://github.com/bitpay/bitcore-node/issues/374
[3]:https://forum.bitcore.io/t/more-than-one-instance-of-bitcore-lib-found/699/7
[4]:https://github.com/bitpay/bitcore-payment-protocol/blob/eb3f82bf0becce0edd0298329742001388e853bc/lib/common.js#L3
[5]:https://gist.github.com/insanity54/7f9a00d9bd015f1becde

**Comment by braydonf** [comment]
Is this with the 1.0.1 release? The browserify build should exclude building with bitcore-lib included.

**Comment by braydonf** [comment]
Sorry, just realized you're in Node.js. I'm not sure how you've setup the libraries, but try:
```
npm init
npm install bitcore-lib --save
npm install bitcore-payment-protocol --save
```

**Comment by insanity54** [comment]
Thanks, that seems to work after creating a fresh project. I wanted to see if I could reproduce the issue, but I'm having trouble doing that.

It might have something to do with the fact that I also had bitcore installed in addition to bitcore-lib and bitcore-payment-protocol.

In my use case, I've got several processes that run independently, which I start up with [Foreman](https://www.npmjs.com/package/foreman).

```
$ cat Procfile
db: couchdb
clock: node clock.js
bitcoin: bitcored
bip70: node bitcoin.js
```
So one process is a bitcore full node, another is node running bitcoin.js which is implementing this BIP70 via bitcore.

Hmm, I'll mess around with it some more.

**Comment by cosmoarunn** [comment]
The error thrown from index.js file, 

`bitcore.versionGuard = function(version) {
  if (version !== undefined) {
    var message = 'More than one instance of bitcore-lib found. ' + 
      'Please make sure to require bitcore-lib and check that submodules do' +
      ' not also include their own bitcore-lib dependency.';
    throw new Error(message);
  }
};`

you can either update the version or mark it 'undefined'.
PS: (It's not an issue of installing bitcore globally )
